pose_gt_file: "/mnt/sda/agrilira4d/dataset/gt_flu/flat/NJFlatB01.txt"
lidar_topic: "/rslidar_points"
radar_topic: "/radar_points"
verbose: true

extrinsics:
   # Rz:180 Ry:-90 Rx:0 
  R_bl: [ 0, 0,  1,
          0, -1, 0,
          1,  0, 0]
  t_bl: [0.0, 0.0, 0.0]
  
  # Rz:0 Ry:-81 Rx:-90
  R_lr: [ 0.1564345,  0.9876884, 0,
          0,  0, 1,
          0.9876884, -0.1564345, 0]
  t_lr: [0.11216, 0, -0.03737]

preprocess:
  pose_num_threshold: 7

  lidar_filter_num: 1
  lidar_blind: 2
          
mapper:
  type: 0 # 0: OctoMapper
  octomap:
    resolution: 0.5
    max_range: 50.0
    hit_prob: 0.7
    miss_prob: 0.4
    occupancy_threshold: 0.5
  